apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb
  namespace: aarbey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: webnodb
        image: aarbey/chal1:v3
        ports:
        - containerPort: 5000
        resources:
@@ -26,14 +74,15 @@ spec:
            memory: "200Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: aarbey
spec:
  selector:
    app: webnodb
  ports:
  - protocol: TCP
    port: 80